src/WebUI/Controllers/ChangeThemeController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class ChangeThemeController : Controller
    {
        private const string d = "blitzer";
        private const string cookie = "projqtheme";
        public ActionResult Index()
        {
            var theme = d;
            if (Request.Cookies[cookie] != null)
                theme = Request.Cookies[cookie].Value;

            var themes = new[] { "base", "black-tie", "blitzer", "cupertino", "dark-hive", "dot-luv", "eggplant", "excite-bike", "flick", "hot-sneaks", "humanity", "le-frog", "mint-choc", "overcast", "pepper-grinder", "redmond", "smoothness", "south-street", "start", "sunny", "swanky-purse", "trontastic", "ui-darkness", "ui-lightness", "vader" };

            var items = themes.Select(o => new SelectListItem { Text = o, Value = o, Selected = o == theme });

            return View(items);
        }

        [HttpPost]
        public ActionResult Change(string[] themes)
        {
            var theme = themes[0];
            Response.Cookies.Add(new HttpCookie(cookie, theme) { Expires = DateTime.Now.AddYears(1) });
            return new EmptyResult();
        }

        public ActionResult CurrentTheme()
        {
            var theme = d;
            if (Request.Cookies[cookie] != null)
                theme = Request.Cookies[cookie].Value;

            return Content(theme);
        }
    }
}

src/WebUI/Views/ChangeTheme/index.cshtml
@model System.Collections.Generic.IEnumerable<System.Web.Mvc.SelectListItem>
<form id="themesform" action="@Url.Action("Change", "ChangeTheme")" method="post">
@Html.DropDownList("themes", Model,new{style="width:100px;"})
</form>
<script type="text/javascript">
    $(function () {
        $('#themes').change(function () {
            $(this.form).ajaxSubmit();
            $("#siteThemeLink").attr("href", "Content/themes/" + $("#themes").val() + "/jquery-ui.css");
            setTimeout('colorfix()', 100);            
            setTimeout('colorfix()', 400);            
        });
    });

    function colorfix() { $('.ui-state-highlight a').css('color', $('.ui-state-default').css('color')); }

</script>