src/WebUI/Controllers/VendorController.cs
using System;
using System.Configuration;
using System.Drawing;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI;
using Core.Model;
using Core.Service;
using Infra.Builder;
using Infra.Dto;
using Omu.Awesome.Mvc;
using Omu.Drawing;

namespace WebUI.Controllers
{
    public class VendorController : Cruder<Vendor, VendorInput>
    {
        private new readonly IVendorService s;
        private readonly IUtilService us;

        public VendorController(IVendorService s, IBuilder<Vendor, VendorInput> v, IUtilService us) : base(s, v)
        {
            this.s = s;
            this.us = us;
        }

        public override ActionResult Index()
        {
            ViewBag.UseList = true;
            return base.Index();
        }

        public virtual ActionResult Search(string search, int? categoryId, int page = 1, int ps = 5)
        {
            var src = s.Where(o => o.Name.StartsWith(search) || o.PinYin.Contains(search), User.IsInRole("admin"));
            if (categoryId != null) src = src.Where(o => o.CategoryId == categoryId);
            var rows = this.RenderView("rows", src.OrderBy(u => u.Id).Skip((page - 1) * ps).Take(ps));

            return Json(new { rows, more = src.Count() > page * ps });
        }

        [OutputCache(Location = OutputCacheLocation.None)]
        public ActionResult Picture(int id)
        {
            return View(s.Get(id));
        }

        [HttpPost]
        public ActionResult Picture()
        {
            var file = Request.Files["fileUpload"];
            var id = Convert.ToInt32(Request.Form["id"]);
            if (file.ContentLength > 0)
            {
                var filePath = @ConfigurationManager.AppSettings["storagePath"] + @"\Vendors\temp\" + id + ".jpg";
                using (var image = Image.FromStream(file.InputStream))
                {
                    var resized = Imager.Resize(image, 640, 480, true);
                    Imager.SaveJpeg(filePath, resized);
                    return RedirectToAction("Crop", new CropInput { ImageWidth = resized.Width, ImageHeight = resized.Height, Id = id });
                }
            }

            return RedirectToAction("Index");
        }

        [OutputCache(Location = OutputCacheLocation.None)]
        public ActionResult Crop(CropInput cropDisplay)
        {
            return View(cropDisplay);
        }

        [HttpPost]
        public ActionResult Crop(int x, int y, int w, int h, int id)
        {
            using (var image = Image.FromFile(@ConfigurationManager.AppSettings["storagePath"] + @"\Vendors\temp\" + id + ".jpg"))
            {
                var img = Imager.Crop(image, new Rectangle(x, y, w, h));
                var resized = Imager.Resize(img, 200, 200, true);
                var small = Imager.Resize(img, 100, 100, true);
                var mini = Imager.Resize(img, 45, 45, true);
                Imager.SaveJpeg(@ConfigurationManager.AppSettings["storagePath"] + @"\Vendors\" + id + ".jpg", resized);
                Imager.SaveJpeg(@ConfigurationManager.AppSettings["storagePath"] + @"\Vendors\" + id + "s.jpg", small);
                Imager.SaveJpeg(@ConfigurationManager.AppSettings["storagePath"] + @"\Vendors\" + id + "m.jpg", mini);

                s.HasPic(id);
            }
            return RedirectToAction("Picture", new { id });
        }

        public override ActionResult Create(VendorInput input)
        {
            input.PinYin = us.ConvertChsToPinYin(input.Name);
            return base.Create(input);
        }

        public override ActionResult Edit(VendorInput input)
        {
            input.PinYin = us.ConvertChsToPinYin(input.Name);
            return base.Edit(input);
        }

    }
}

src/WebUI/Views/Vendor/create.cshtml
@model VendorInput
@using (Html.BeginForm())
{
    @Html.EditorFor(o => o.Name)
    @Html.EditorFor(o => o.CategoryId)
    @Html.EditorFor(o => o.Comments)
}

src/WebUI/Views/Vendor/crop.cshtml
@model CropInput
@{
    ViewBag.Title = "Picture";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="@Url.Content("~/Content/jquery.Jcrop.css")" rel="stylesheet" type="text/css" />
<script type="text/javascript" src='@Url.Content("~/Scripts/jquery.Jcrop.min.js")' ></script>

<script language="Javascript" type="text/javascript">

        $(function() {
            jQuery('#cropbox').Jcrop({
                setSelect: [ 0, 0, 200, 150 ],
                onChange: showPreview,
                onSelect: showPreview,
                aspectRatio: 1.333
            });
        });
        
         function updateCoords(c) {
		        jQuery('#x').val(c.x);
		        jQuery('#y').val(c.y);
		        jQuery('#w').val(c.w);
		        jQuery('#h').val(c.h);
		    }

        function showPreview(coords) {
        updateCoords(coords);
        
            if (parseInt(coords.w) > 0) {
                var rx = 200 / coords.w;
                var ry = 150 / coords.h;

                jQuery('#preview').css({
                    width: Math.round(rx * @Model.ImageWidth) + 'px',
                    height: Math.round(ry * @Model.ImageHeight) + 'px',
                    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
                    marginTop: '-' + Math.round(ry * coords.y) + 'px'
                });
            }
        }		
</script>
<div style="margin:auto; width:900px;">
<div style="float:left;" >
    <img src='@Url.Content("~/pictures/Vendors/temp/"+Model.Id+".jpg")' id="cropbox" alt="crop" />
</div>
<div style="width: 200px; height: 150px; overflow: hidden;float:right;">
    <img src='@Url.Content("~/pictures/Vendors/temp/" + Model.Id + ".jpg")' id="preview" alt="thumb" />
</div>
<br class="cbt"/>
<br />
@using(Html.BeginForm()) {
    <input type="hidden" id="x" name="x" />
    <input type="hidden" id="y" name="y" />
    <input type="hidden" id="w" name="w" />
    <input type="hidden" id="h" name="h" />
    <input type="submit" value="@Mui.select_thumbnail" />
        }
        </div>

src/WebUI/Views/Vendor/header.cshtml
<h2>@Mui.Vendor</h2>

src/WebUI/Views/Vendor/picture.cshtml
@model Vendor
@{
    ViewBag.Title = "Picture";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    @Mui.Picture @Model.Name</h2>

 <img  src='@Url.Content("~/pictures/Vendors/" + (Model.HasPic ? Model.Id : 0) + ".jpg?"+DateTime.Now.Ticks.ToString())'  alt='picture' />
@using (Html.BeginForm("Picture", "Vendor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{     
    <input type="hidden" id="id" name="id" value="@Model.Id" />
    <input type="file" id="fileUpload" name="fileUpload" />
    <input type="submit" value="@Mui.upload_file" />   
}

src/WebUI/Views/Vendor/rows.cshtml
@model IEnumerable<Vendor>

@foreach (var o in Model)
{
    <li id='o@(o.Id)' class="meal">
        <div>@o.Name
            <div class="fr">
            @Html.Partial("deletebtn",o)            
            </div>
        </div>
        <div>
            <div class="fl"><img  src='@Url.Content("~/pictures/Vendors/" + (o.HasPic ? o.Id : 0) + ".jpg")' class="thumb"  alt='picture' /></div>
            @*<div class="fl">@Html.ActionLinkWithImage(@Url.Content("~/pictures/Vendors/" + (o.HasPic ? o.Id : 0) + ".jpg"), "Open", parameters: new object[] {o.Id}, imgHtmlAttributes: new {@class = "thumb", @alt="picture", @title=@Mui.Open})</div>*@
            <div class="comments">@o.Comments</div>
            <br class="cbt"/>
        </div>        
        <div class="cbt">
            @Html.ActionLink(@Mui.Picture, "Picture", new { o.Id })
            <div class="fr">@Html.PopupFormActionLink("Edit", @Mui.Edit, parameters: new object[] { o.Id })</div>
        </div>        
    </li>
}

src/WebUI/Views/Vendor/searchBox.cshtml

@Mui.Search: <input type='text' name='search' />@Mui.VendorCategory:@Html.AjaxDropdown("CategoryId", prefix:"search")
<br class="cbt"/>